version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-minis3}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  node1:
    build:
      context: ./storage-node
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9091:9091"
    volumes:
      - ./data/node1:/data:rw
    environment:
      SERVER_PORT: 9091
      STORAGE_BASE_DIR: /data
      STORAGE_MAX_FILE_SIZE: ${STORAGE_MAX_FILE_SIZE:-10MB}
      STORAGE_ALLOWED_EXTENSIONS: ${STORAGE_ALLOWED_EXTENSIONS:-txt,pdf,doc,docx,jpg,jpeg,png,gif,zip,rar,bin}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  node2:
    build:
      context: ./storage-node
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - ./data/node2:/data:rw
    environment:
      SERVER_PORT: 9092
      STORAGE_BASE_DIR: /data
      STORAGE_MAX_FILE_SIZE: ${STORAGE_MAX_FILE_SIZE:-10MB}
      STORAGE_ALLOWED_EXTENSIONS: ${STORAGE_ALLOWED_EXTENSIONS:-txt,pdf,doc,docx,jpg,jpeg,png,gif,zip,rar,bin}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  node3:
    build:
      context: ./storage-node
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9093:9093"
    volumes:
      - ./data/node3:/data:rw
    environment:
      SERVER_PORT: 9093
      STORAGE_BASE_DIR: /data
      STORAGE_MAX_FILE_SIZE: ${STORAGE_MAX_FILE_SIZE:-10MB}
      STORAGE_ALLOWED_EXTENSIONS: ${STORAGE_ALLOWED_EXTENSIONS:-txt,pdf,doc,docx,jpg,jpeg,png,gif,zip,rar,bin}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-minis3}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-password}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  postgres_data:
