server:
  port: ${SERVER_PORT:9090}
  # Security: limit request size and add timeout
  max-http-header-size: 8KB
  connection-timeout: 30s

storage:
  base-dir: ${STORAGE_BASE_DIR:./data}
  # Security: file size limits and validation
  max-file-size: 10MB
  allowed-extensions: ${STORAGE_ALLOWED_EXTENSIONS:txt,pdf,doc,docx,jpg,jpeg,png,gif,zip,rar,bin}

# Performance: optimize file operations
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}

logging:
  level:
    root: info
    com.example.storagenode: debug
    org.springframework.web: warn
